<div class="container-fluid p-0 m-0" id="check" style="display: none;">
    <div class="row d-flex flex-column" style="height: 100%;">
        <div class="col-6" style="flex-grow: 1;">
            <table class="table table-responsive" style="font-size: 19px; width: 60%; box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px;">
                <thead class="table-light">
                    <tr>
                        <th class="training text-start" style="padding-right: 20px; width:100%;">Attendance Training</th>
                    </tr>
                </thead>
                <tbody id="training-tbody">
                    <!-- Rows will be dynamically inserted here -->
                </tbody>
            </table>
        </div>
        <div class="col-6" style="align-self: flex-end; width:100%;">
            <div class="training-tab-content">
                <div class="training-calendar">
                    <div id="current-month"></div>
                    <table id="calendar-table">
                        <thead>
                            <tr>
                                <th>Sun</th>
                                <th>Mon</th>
                                <th>Tue</th>
                                <th>Wed</th>
                                <th>Thu</th>
                                <th>Fri</th>
                                <th>Sat</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Rows will be dynamically generated by JavaScript -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
